version: '3'

services:
  ollama:
    build: ./llama
    image: ollama/ollama
    container_name: ollama
    volumes:
      - instalily_ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]
    networks:
      - instalily-net

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - instalily-net
    volumes:
      - instalily_volumedb:/data/db

  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - instalily-net
    depends_on:
      - mongodb
      - ollama

volumes:
  instalily_ollama:
  instalily_volumedb:

networks:
  instalily-net:
    driver: bridge