version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - instalily_ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]
    networks:
      - instalily-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - instalily-net
    volumes:
      - instalily_volumedb:/data/db

  server:
    image: server
    container_name: server
    ports:
      - "8000:8000"
    networks:
      - instalily-net

volumes:
  instalily_ollama:
  instalily_volumedb:

networks:
  instalily-net:
    driver: bridge