version: '3'

services:
  milvus:
    image: milvus:v2.4.13
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    volumes:
      - milvus_data:/var/lib/milvus
    networks:
      - instalily-net

  attu:
    image: zilliz/attu:v2.4
    container_name: attu
    environment:
      - MILVUS_URL=milvus:19530
    ports:
      - "8080:3000"
    depends_on:
      - milvus
    networks:
      - instalily-net

  ollama:
    image: ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]
    networks:
      - instalily-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - instalily-net

  server:
    image: server:latest
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - "ollama"
      - "mongodb"
      - "milvus"
    networks:
      - instalily-net

volumes:
  milvus_data:
  ollama_data:
  mongodb_data:

networks:
  instalily-net:
    driver: bridge