version: '3'

services:
  ollama:
    build: .
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]

volumes:
  ollama: